language: python
sudo: required

dist: trusty

# matrix
python:
  - 2.7
  - 3.5
env:
  - CKANVERSION=master

# tests
services:
  - postgresql
  - redis-server
install:
  - bash bin/travis-build.bash
  - pip install codecov
script: sh bin/travis-run.sh

after_success:
    - codecov

# additional jobs
matrix:
  include:
    - name: "Flake8 on Python 3.7"
      dist: xenial    # required for Python 3.7
      cache: pip
      install: pip install flake8
      script:
        - flake8 --version
        - flake8 . --count --max-complexity=10 --max-line-length=127 --statistics --exclude ckan,ckanext-create_typed_package
      python: 3.7
      # overwrite matrix
      env:
        - FLAKE8=true
        - CKANVERSION=master
